### PR TITLE
Implementing dashboard authorization filter.

### PR DESCRIPTION
**Pull request by mo-esmp**
Unifying authentication and authorization mechanism like the Hangfire [dashboard](https://docs.hangfire.io/en/latest/configuration/using-dashboard.html)!

### CODE REVIEW

**Comment by followynne** [comment]
Hey @mo-esmp,

Love the idea of going with the Hangfire authorization style! 🤗 I'm not sure when but I'll try to read and review the PR as soon as possible 😉

(fyi, I'm going onwards with the integration test pr - I just need to complete elastic ones and a small mongo-test refactor to merge that part. I'll write you about it when I complete it 😄)

**Review by sommmen — COMMENTED** [review]
LGTM!

**Review by followynne — COMMENTED** [review]
Hey @mo-esmp 

I reviewed the PR - IMHO, it's a great feature, all green from me! In the feature we could think if it can be useful to add any auth related to policies/etc, right now I'd merge it ASAP 😄 

A quick suggestion: I made a small cleanup branch on the tests naming etc here https://github.com/followynne/serilog-ui/tree/chore/ui-web-cleanup, give it a look if you think it's good to include on your branch 😃 

A quick notice, on test "Local_Request_are_allowed_by_default": I saw it fails if the front end build wasn't run before launching it- in the future I'll try to see if there's a way to prevent this 😃

**Review by followynne — APPROVED** [review]

**Comment by followynne** [comment]
(@mo-esmp I already approved the PR as per prev comment)

**Comment by mo-esmp** [comment]
@followynne Please send your PR to this one, `setup-ci`  branch needs more work. I need to figure out how run tests that need Docker in GitHub environment. Before sending the PR, please rename `Util` to `Utility`. Let's have this convention to use the full name instead of an abbreviation (choosing `Implementation` over `Impl`).

**Comment by followynne** [comment]
@mo-esmp yep, all good 🛩️ 
 I opened #67 to merge the chore on this branch (then you can merge it), let me know if anything else 😃

**Pull request merged**
