### PR TITLE
Proposal: refactor assets to use typescript, modern bundler

### PR DESCRIPTION
**Pull request by followynne**
## Description 
This PR aims to refactor the Serilog.Ui.Web frontend assets to improve future maintainability and simplify any contributor work, by replacing the deprecated bundleconfig.json with a modern JS bundler.
Extra: to develop the frontend, ParcelJS starts a local webserver. Behind the scenes, msw intercepts any data-fetch and replace them with static data from assets/scripts/mocks/samples.ts. Any filter is applied in src/Serilog.Ui.Web/assets/script/mocks/fetchMock.ts.

### Bundling Refactor features

- use [ParcelJs](https://parceljs.org/) to bundle assets and produce production version into dist/
- add Grunt tasks to simplify usage of parcel scripts
- replace static files dependencies with their npm package version
- commit a first production-version
- add [msw](https://mswjs.io/) to mock outbound queries during development
- add assets-development info on the README

## refactors 

- convert the project to [Typescript](https://www.typescriptlang.org/) while adding project typings
- restructure the project in files
- replace all jQuery functions (except those required by bootstrap or netstack.js) with plain JS
- use [date-fns](https://date-fns.org/) for dates manipulation

## features

- added a new authenticationSingleton class to retrieve config info
- added a new clickable button in pagination onto: [...] => it lets the user go to a precise page

## fixes

- (pagination): fix extra pages buttons that were rendered when the (currentPage + 5) <= totalPages

### CODE REVIEW

**Comment by followynne** [comment]
Hi @mo-esmp,

I had some time to play with the project and, well...😄 
I noticed that the frontend was a bit difficult to develop so this PR wants to replace the bundleconfig.json-style build, which is deprecated, with a modern JS bundler (I choose ParcelJs as it's completely automatic.  

This wants to simplify any future maintenance and collaboration on the front end. For that reason, I adopted typescript and replaced jQuery almost everywhere. You can find all the updates in the PR description...

If you'd like it, another improvement could be the complete jQuery removal and the update of bootstrap to bootstrap 5 😸 (the only real requirement would be to identify a replacement for netstack.js but I think it's possible to find it...)  

Let me know if you like it or if there's any doubt about it... if it's fine for you and you think it's good, I can promote the draft to an actual PR 🛩️ 

(ps I have another pr almost ready to add a sort option to the dashboard 😄 https://github.com/followynne/serilog-ui/tree/feature/add-sort-options)

**Comment by mo-esmp** [comment]
@followynne Thank you for the PR and I appreciate that. I'll review it ASAP, these days I'm really busy and it will take some time.

**Comment by mo-esmp** [comment]
@followynne again I appreciate your work. There are some issues:
 
- There is an error in the authentication ts file and there is no JWT input in UI
image

- If fill search parameters, for example, If select a start date or type in search message input then click on paging and choose another page to display data, logs won't be shown

Hence I'm not an expert in UI (from jQuery age as you know :), I would be glad if we have a short conversation about the new UI structure. Also if you are interested I can add you as a collaborator.

**Comment by followynne** [comment]
Hi @mo-esmp,

thanks a lot for reviewing 😄 about your (correct, I'm sorry I missed those ones) notes, I made some fixes:

- I added a try-catch on the config input that the UI receives from Serilog Middleware. During development the SerilogUI .Net Project isn't started thus it doesn't inject the config info; the try-catch should prevent any breaking-issue on Production!
- I improved the search for dates and text input in the mocked fetch (here: the [commit](1839b801b68d50c4024a63754241e31b3b1cf5d8)); the best way to check if the UI works are to start the Serilog sample and use the production bundle from /dist. 
**addendum: if it also happens when in production, I'll try to review the sorting/search options in the next branch I'm working on by checking directly the providers 👍 

About the chat, sure, I'll be happy to talk about it! Feel free to contact me when you have time on [telegram](https://t.me/MatteoGregoric), I'll answer you as soon as I can 💯

**Pull request merged**
