### PR TITLE
chore(npm): bump, fix js-build sonar step

### PR DESCRIPTION
**Pull request by followynne**
Hello @mo-esmp 

this PR wants to:

- bump npm dependencies, removing vulnerability issue (I'm closing #77 as this should be more comprehensive)
- fix JS Build sonar step (which was always skipped - right now it should work when run isn't on PR)

### CODE REVIEW

**Comment by followynne** [comment]
Hello @mo-esmp 

just FYI, I started the React development on this branch https://github.com/followynne/serilog-ui/tree/feat/react-ui, if you want to take a peek 😄 

(migrating the functionalities right now to mantine-react + react-form-hooks + react-query, to use state-of-art pkgs, later I'll fix the style 😆 )

**Review by mo-esmp — APPROVED** [review]

**Comment by mo-esmp** [comment]
@followynne Thanks for the PR. About migrating to react, I would like to participate hence I want to use this approach for other libraries. If you share some information about the basic of work, I would be grateful.

**Comment by followynne** [comment]
@mo-esmp 

hey, sorry for the late answer, I didn't work on it in the last couple of weeks - writing you now the current status of the work and some info!

Branch is https://github.com/followynne/serilog-ui/tree/feat/react-ui, I added a couple of commits in the last days to clean&fix some broken pieces 🤣 

- first of all, I added/improved the configurations for [prettier](https://prettier.io/) and [eslint](https://eslint.org/). With this solution prettier (there's a vscode ext) gives us code style rules and eslint gives quality-js error/warnings to improve the code. There are some npm scripts to use that runs eslint or run prettier (with auto-style-update)
 
- I refactored the UI.Web C# part to try to split and improve clarity of the endpoints, plus getting us an easier way to test this part in the future. Right now I didn't test it in practice - I expect that I still have some work to do on the whole Authorization parts...

- the Parcel configuration is updated to add React & JSX compilation 
- almost all the index.html code has been dropped and replaced by a single div, with id, because in the main react entry file we get that element and use it to attach the React application
- the UI system is based on [mantine.dev](https://mantine.dev/), 'cause I liked the style and it had all the ready-for-use components the app needed (included AppShell for the app structure!) plus it makes really easy CSS-styling (and light-dark mode)
- for the http reqs part, I'm using [react-query](https://tanstack.com/query/latest/docs/react/overview) as I heard really good things about it

- I'm migrating the app piece by piece; if you check the old app code you'll find it "broken" because I'm deleting old code lines as soon as their functionality is replicated in React. As of today, the pagination is missing while most of the rest (not complete) is available in draft mode...

Let me know if I can add any additional info I didn't think in the first place :)
Also, if you find it useful, I can prepare a bare parcel+react template to be used for any new project, just let me know!

**Comment by mo-esmp** [comment]
@followynne Thanks for enlighting me. I will follow the change on the repo to learn more about the implementation.

**Pull request merged**
