### PR TITLE
Fix/missing serilog level

### LINKED ISSUE #29: Level "Critical" not supported
I can't filter my logs by Level "Critical".
When I add a critical entry, no level is displayed for the entry.

image

### PR DESCRIPTION
**Pull request by followynne**
Fixes #29 (cc @E4est)

It adds the log level "Critical" to the FE options.

@mo-esmp, do you think it could be possible first to produce an alpha/beta package and then to release a new official version of the library?

I'd like to run a small test on a personal project that is released outside of localhost, to check if the FE runs all fine 😸
(I don't know if it should be tagged as a major version, as it was mainly a refactoring...)

If you'll be able to produce an alpha release, I'll test it ASAP 👍 

Thanks a lot!

### CODE REVIEW

**Comment by mo-esmp** [comment]
Yes, for significant changes, first we publish a beta package but for minor changes, I think it's not necessary. 
Is the `dist` folder required to be checked in? If not please add it to the `.gitignore` file.

**Comment by followynne** [comment]
Okay! I'd still prefer to go with a quick beta pkg, as the build system to produce the frontend assets changed and it would be better to give it a trial without a stable release...

About the dist folder, a question: are the assets built and copied into the package during the package creation? (I'm thinking at [this one](https://github.com/mo-esmp/serilog-ui/commit/5c2261cc1e89c3a0e3d785ab474dd011acf4d141#diff-88a00bd129cc0793e3556baa66520197c5f378ce8d19701d1f80dc3ce37f9780))

I'm not an expert on this topic... I committed dist to have a built assets version inside the package; if the FE gets built and copied to the final artifact during the NuGet pack phase, we can git-ignore it 👍 
Let me know and I'll update the PR 😃

**Comment by mo-esmp** [comment]
Sorry, busy relocating. I guess tomorrow I shall have a chance to discuss and merge the PR and release the beta package.

**Comment by mo-esmp** [comment]
@followynne Could you please fix the merge conflict?

**Comment by followynne** [comment]
@mo-esmp 

sure, fixed conflict (and gitignored the UI built code, as I noticed it'll get compiled on build) 😃

**Comment by mo-esmp** [comment]
Published Serilog.UI 2.1.2-beta package.

**Comment by followynne** [comment]
Awesome, thanks a lot! Tomorrow morning I'll update it and test in a small Prod project and report back :)

**Comment by followynne** [comment]
@mo-esmp 

I think the beta package was released from master and not dev, as I tested now but I couldn't find any expected change.

example:
I would expect to see this small change from
https://github.com/mo-esmp/serilog-ui/commit/d51eba03b3ac256d2961196e0615c7791a36a10c

but the source code from beta doesn't contain it:
image

**Pull request merged**
