### PR TITLE
chore: release serilog-ui 2.6.0

### PR DESCRIPTION
**Pull request by followynne**
This PR:

- bump version to 2.6.0
- add PrivateAssets="true" to packable projects, to make them packable from dotnet pack
- add direct project reference on sub-packages (SampleApp, Web.Tests)
- add packageid on serilog.ui.web, to have dotnet pack automatically create the correct package name

### CODE REVIEW

**Comment by followynne** [comment]
hello @mo-esmp 

I prepared a PR for the 2.6 release, as soon as it's merged I'll push the package to Nuget :)

**Review by mo-esmp — APPROVED** [review]

**Comment by mo-esmp** [comment]
@followynne Thanks a lot.

**Comment by followynne** [comment]
Hey @mo-esmp !

2.6.0 released :)
I took some time to update/review the Releases page, creating a sort of release history while making all tags listed in Nuget available in the repo. I suggest you to run in your local repo

```
git tag -d $(git tag -l)
git fetch origin
git fetch origin --prune
```

to delete local tags and fetch a clean situation, as I did modify some tags etc...

Have a nice week! 👍

**Comment by mo-esmp** [comment]
Thanks for the effort, I will do it and likewise.

**Pull request merged**
