### PR TITLE
Improve date management and manipulation

### PR DESCRIPTION
**Pull request by followynne**
Hi @mo-esmp,

this PR aims to improve the date-time management in the serilog-ui middleware.

- removed in the middleware the endDate manipulation, as the UI now has selectable date & time
- identify the parsed dates as Local (based on the input received from the UI)
- updated MongoDbDataProvider to use UtcTimeStamp, since the TimeStamp provider is empty until model normalization
- (chore) remove npm i target from Serilog.Ui.Web, due to VS issues with locking files. The packages installation will be issued manually by the dev on the first run 👍

### CODE REVIEW

**Comment by mo-esmp** [comment]
Thanks for the PR. Other data providers should be checked and need to find a way to add integration tests against databases to avoid manual testing every time.

**Comment by followynne** [comment]
You're right, I went straight with a fix for Mongo as it's the provider I currently use and I noticed it early 😊 SQL-like should be fine, from the table structure, probably Elastic-provider should be double checked (it can be done in a separate pr). 

On Integration tests, I have it on my todo: create the test env and then  start adding some integration for Mongo (already been there, already did them) 😁 don't have an ETA but I'll do that 😊

**Comment by followynne** [comment]
Hi @mo-esmp,

sorry for the late, I aligned the branch to master and checked ElasticSearch date search result - from my check it works fine, thus if you want to merge the PR it should be all clear (SQL should be already good) 😄 

(tests will go on a separate branch)

**Comment by mo-esmp** [comment]
Hey @followynne, Thanks again to double check, for the weekend I will have time to check the PR and sorry for delay.

**Comment by mo-esmp** [comment]
Is this PR still relevant?

**Comment by followynne** [comment]
> Is this PR still relevant?

Yes - if I remember correctly, it was a small fix to improve timezone management with MongoDb 2 datetime fields 😃 
I'd merge it, if you're okay with it!

(I also added the test fix for Mongodb package 2.19, if you have time to re-try them...)

**Review by mo-esmp — APPROVED** [review]

**Pull request merged**
