### PR TITLE
tests(data-providers): integration tests

### PR DESCRIPTION
**Pull request by followynne**
This PR creates the test suite for the existing data providers and prepares a set of interfaces and default implementations that any future Data Provider could implement, to provide a valid set of expected test cases.

Additional information:
- I made a default implementation for all the interfaces, that can be reused on new ones (it only needs the IIntegrationRunner configuration)
- mongodb uses MongoDbRunner as the integration framework
- mysql, mssql, postgres uses TestContainers
- elasticsearch uses ElasticSearch.Xunit cluster framework*
- I noticed that sometimes a project can fail due to Refused Connection to [...] - usually it's only related to the machine that runs the tests, when it happens I only run the affected project and it works 😄 

*fyi: I tried for months to use TestContainers on Elastic but I couldn't understand how to solve connectivity issues - right now I was finally able to create this implementation, we can review it later if we prefer another one :)

Traits view:

immagine

### CODE REVIEW

**Comment by followynne** [comment]
Hello @mo-esmp,

I finally (finally - too many months lost on the Elastic tests 😆 ) completed the integration tests for the DataProviders (at least, I hope so).

I added all info in the PR description, let me know if there's anything else I missed 👍 
I hope they work fine, my last run after merging dev was fine thus... I hope they run 🛩️ 

In my opinion, if you test the branch and are fine with it, we could merge it and then we'll be able to review&merge the other PRs (I'd start with yours, if we merge this one 😄 ). Let me know if you agree!

(tests for Ui.Web and frontend will come in a separate PR, ottherwise we'll never merge it 🤣 )

(oh, if it's ok for you, please squash the PR when merging - I made too many commits 🍡 )

**Comment by mo-esmp** [comment]
@followynne I appreciate your time and effort in adding tests, it's great work. I'm going to run tests and if everything is fine, I'll approve PRs and merge them. There is always room for improvement and later we will discuss the way to improve tests.
After merging all existing PRs, I'll move the repo to the Serilog-contrib organization and if @sommmen is ok I can also add him as a team member there.

**Comment by sommmen** [comment]
> @followynne I appreciate your time and effort in adding tests, it's great work. I'm going to run tests and if everything is fine, I'll approve PRs and merge them. There is always room for improvement and later we will discuss the way to improve tests. After merging all existing PRs, I'll move the repo to the Serilog-contrib organization and if @sommmen is ok I can also add him as a team member there.

Sure I'd be happy to help out!

**Comment by followynne** [comment]
> @followynne I appreciate your time and effort in adding tests, it's great work. I'm going to run tests and if everything is fine, I'll approve PRs and merge them. There is always room for improvement and later we will discuss the way to improve tests.
> After merging all existing PRs, I'll move the repo to the Serilog-contrib organization and if @sommmen is ok I can also add him as a team member there.

Agreed, that's a great idea for me, @sommmen will be a great addition!

About the project move, that's a nice one - I'll try to review your 2 prs in the next days. About the others I opened, I'll update and check them and I'll write you a comment on each, specifying if it's ok for a check/merge or if I'll close it (to reopen them later on the migrated repo). 🦭🤗

**Comment by mo-esmp** [comment]
Approved PR, but some Mongo tests failed for me.

image

**Review by mo-esmp — APPROVED** [review]

**Comment by followynne** [comment]
> Approved PR, but some Mongo tests failed for me.
> 
> image

I found https://stackoverflow.com/a/75637412/15129749 on the topic, I'm fixing those into #34 😄

**Pull request merged**
