### PR TITLE
Add a SORT-BY option to the UI

### PR DESCRIPTION
**Pull request by followynne**
# Scope

Add a new sort option to the user interface.

## How it works

- new dropdown in the UI, with the option to select a preferred Property + Direction
- new parameter in the Log Provider interface, to admit passing these 2 info
- implementation of the reviewed interface in all providers

## Fixes

In MongoDb and Elastic providers, the LINQ query order was changed to:

ProviderORMEntry => +Query => +Sort{Prop}{Direction} => +Skip{n} => +Take{n}

### CODE REVIEW

**Comment by mo-esmp** [comment]
Hey @followynne,
Just like always sorry for the late reply. Hence the project does not have any tests, I was about to add some tests and found these articles:
- [Integration Test with Docker and .Net6](https://medium.com/geekculture/integration-test-with-docker-and-net6-564cb4922cfd)
- [ASP.NET Core Integration Tests with Test Containers & Postgres](https://www.azureblue.io/asp-net-core-integration-tests-with-test-containers-and-postgres)

I want to know what is your idea about this matter, should we add tests and then merge and or merge and then add tests? Hence there are several data providers and it's hard to set up and run a sample project to test different data providers manually.

**Comment by followynne** [comment]
Hey there @mo-esmp,
Don't worry, there's no hurry - when I have time I play around 😄

I get your point, it's painful to not being able to run some tests before merging PR with new feats.
I did a integration test suite setup on Sql Server a couple of weeks ago for work, if it's fine for you I can try replicating it along with one for Mongo and then discuss with you the outcome 😊

About the PR, we can leave it open or merge it without releasing (1st option is better, as I'll commit to create tests soon) - I'll try to squash the Test PR this weekend, if I have time, and setup at least a couple of providers 🎾

**Comment by mo-esmp** [comment]
Thanks @followynne. This weekend finally I can set up my home-office env and be able to focus on writing codes after a long time and start adding tests. As soon as I started, I will let know that I'm going to add tests for what data providers. I guess it's the right time to move the project to Serilog-Contrib and add you as a maintainer and hope to be able to do that this weekend.

**Comment by followynne** [comment]
Ciao @mo-esmp 

That's fantastic news, it's great to hear it!

FYI, those days I worked on creating the tests structure and the MongoDB tests, as I already did them in a different project 😃 

You can give a check to the branch in this [draft PR](https://github.com/mo-esmp/serilog-ui/pull/44), if you like it we can work on that branch and add the remaining 👍

For MongoDB, I didn't use _testcontainers_ as MongoRunner is an excellent package to use for integration testing. For the SQL providers, I think we should go with it 100% 😉 (it looks like an awesome project, thanks 1000 for sharing the discovery!)

(I'll try to do the same base test configuration for the JS part asap...)

**Comment by followynne** [comment]
@mo-esmp

FYI: I'll leave this PR here and close it soon. I'll reopen it later updated and with tests in the new repo 😊

**Pull request closed without merging**
