### PR TITLE
feat(provider): add SQLite sink support

### PR DESCRIPTION
**Pull request by kzeedev**
Hi @followynne
I've made Sqlite support, some tests are failing because no TestContainers found for Sqlite so changed tests to use InMemory database instead but base classes use TestContainer.
Please take a look on it.

### CODE REVIEW

**Comment by mo-esmp** [comment]
@techgarage-ir Thanks for the PR. We will review it soon.

**Comment by followynne** [comment]
Hi @techgarage-ir 

thanks a lot, really appreciate it!!

I'll try do understand how to make tests work with the TestContainer package, I'd prefer it as it would give us a better integration suite.

Just to let you know, I'll check the PR after we complete v3 development - this will require a small update to your implementation to align to the modified API.

Just to know, do you prefer 
- I comment on this PR about required changes or 
- I create a branch with the changes and open a PR towards your personal branch?

Thanks a bunch 🥇

**Comment by kzeedev** [comment]
Hi again

So good, I'm looking for v3.

That's not matter, do what's your usual in project and I'll make required changes asap.

**Comment by followynne** [comment]
@techgarage-ir 

as an update, I started working on a branch towards yours, to align with v3 and fix anything I find 😄

**Comment by kzeedev** [comment]
That's great, I've used v2 with Sqlite on a project and found just one bug that's log time is in incorrect timezone, but I guess that's being fixed in v3 due to [this](https://github.com/serilog-contrib/serilog-ui/issues/126#:~:text=dates%20can%20be%20displayed%20in%20UTC%20or%20in%20the%20user%20browser%20timezone) note.

**Comment by mo-esmp** [comment]
@techgarage-ir could you please update `SqliteDataProvider` based on the latest changes?
Please check [SqlServerDataProvider.cs](https://github.com/serilog-contrib/serilog-ui/blob/master/src/Serilog.Ui.MsSqlServerProvider/SqlServerDataProvider.cs) and [SqlServerQueryBuilder.cs](https://github.com/serilog-contrib/serilog-ui/blob/master/src/Serilog.Ui.MsSqlServerProvider/SqlServerQueryBuilder.cs) classes and update your PR accordingly.

**Comment by followynne** [comment]
FYI: test update WIP.

**Comment by kzeedev** [comment]
> @techgarage-ir could you please update `SqliteDataProvider` based on the latest changes? Please check [SqlServerDataProvider.cs](https://github.com/serilog-contrib/serilog-ui/blob/master/src/Serilog.Ui.MsSqlServerProvider/SqlServerDataProvider.cs) and [SqlServerQueryBuilder.cs](https://github.com/serilog-contrib/serilog-ui/blob/master/src/Serilog.Ui.MsSqlServerProvider/SqlServerQueryBuilder.cs) classes and update your PR accordingly.

Yes, I'll check it ASAP.

**Comment by followynne** [comment]
> > @techgarage-ir could you please update `SqliteDataProvider` based on the latest changes? Please check [SqlServerDataProvider.cs](https://github.com/serilog-contrib/serilog-ui/blob/master/src/Serilog.Ui.MsSqlServerProvider/SqlServerDataProvider.cs) and [SqlServerQueryBuilder.cs](https://github.com/serilog-contrib/serilog-ui/blob/master/src/Serilog.Ui.MsSqlServerProvider/SqlServerQueryBuilder.cs) classes and update your PR accordingly.
> 
> Yes, I'll check it ASAP.

Hi @techgarage-ir ,

Fyi, I already pushed the updated code to your repo and was working on fixing tests. 
Please give it a look and a test if you have time,especially for the new sort feature, thanks!

**Comment by kzeedev** [comment]
> > > @techgarage-ir could you please update `SqliteDataProvider` based on the latest changes? Please check [SqlServerDataProvider.cs](https://github.com/serilog-contrib/serilog-ui/blob/master/src/Serilog.Ui.MsSqlServerProvider/SqlServerDataProvider.cs) and [SqlServerQueryBuilder.cs](https://github.com/serilog-contrib/serilog-ui/blob/master/src/Serilog.Ui.MsSqlServerProvider/SqlServerQueryBuilder.cs) classes and update your PR accordingly.
> > 
> > 
> > Yes, I'll check it ASAP.
> 
> Hi @techgarage-ir ,
> 
> Fyi, I already pushed the updated code to your repo and was working on fixing tests. Please give it a look and a test if you have time,especially for the new sort feature, thanks!
Hi

That's fine, I'm looking at it and will use it on some test projects to get more details.

**Comment by followynne** [comment]
That's awesome, thanks! I'll try to complete the tests this weekend and notifiy you for a final greenlight 👍

**Review by followynne — APPROVED** [review]

**Comment by followynne** [comment]
Hi @techgarage-ir 

code updated to final version, I fixed issues with the Datetime querying (since field is a text, it wasn't working correctly), feel free to give it a try - if you're okay with it, we can close the PR!

@mo-esmp 
I added you as a reviewer, to let you give the code a double check since you did the latest sql-refactoring 😄 on my side we're fine and we close the PR 👍

**Review by mo-esmp — APPROVED** [review]

**Comment by mo-esmp** [comment]
Thanks for the contribution, @techgarage-ir.
@followynne please publish the NuGet package and add me as an owner.

**Pull request merged**
