### PR TITLE
Fix (#96) improve datetime parsing on sql server

### LINKED ISSUE #96: Timestamp returned as Jan 1, 1901 0:00:00.000
Using Serilog.UI.MsSqlServerProvider all timestamps are displayed in the UI as 'Jan 1, 1901 0:00:00.000'

Screenshot 2023-10-31 164910-2

This stems from the value returned in the http request:

"timestamp": "0001-01-01T00:00:00"

However filtering by time period works fine so it seems to be able to read the datetime correctly for that purpose.

**To Reproduce**
Created an empty Blazor web app, added these packages:
Serilog.UI 2.5.0
Serilog.UI.MsSqlServerProvider 2.2.2

Only configuration was to specify the connection string, table name and schema using 'UseSqlServer'

**Expected behavior**
To display the datetimes from the database. Example rows from the table:

Screenshot 2023-10-31 165024

### PR DESCRIPTION
**Pull request by followynne**
This PR aims to fix #96, by changing the default datetime parsing in MS SQL Provider. 

The default parse will assume that the date saved in the database is related to the application culture, assuming it's local based.

If the user isn't satisfied by the default parsing, a new parameter can be used to customize the datetime parsing. The DateTime produced must be UTC-kind or the app will throw an exception.

EDIT: it also bumps npm libraries (will close the other PRs later)

### CODE REVIEW

**Comment by followynne** [comment]
Hello @mo-esmp,

I tried a fix for #96 + added Teronis package to package the nuget with the referenced dll (I didn't find a way to dotnet pack and include the reference to serilog.ui.core...)

If you like both changes, I'd move onwards and publish an alpha version for mssql provider, to let users test it (and test nuget publication from my side) 😄

**Comment by mo-esmp** [comment]
Sorry for the late response. Do we need to add some tests regarding the bug? because for me it is still unclear under what circumstances this bug can happen.

**Comment by followynne** [comment]
@mo-esmp 

tests added, let me know if the bug and its fix are more clear 😄

**Review by mo-esmp — APPROVED** [review]

**Comment by mo-esmp** [comment]
Thanks for adding tests.

**Pull request merged**
