### PR TITLE
fix(#99): replace xml formatting, prevent double format

### LINKED ISSUE #99: XML output isn't rendered correctly
**Describe the bug**
Opening the properties details view multiple times does funny things to rendered xml. `<test>` becomes `&lt;test&gt;`, closing and opening another time will produce `&amp;lt;test&amp;gt;`

**To Reproduce**
1. Go to dashboard
2. Click on 'View'
3. Close dialog
4. Click on 'View' again
5. See < being converted to &lt;

**Expected behavior**
The details dialog should show xml tags.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 120

**Smartphone (please complete the following information):**

**Additional context**

### LINKED ISSUE #108: BUG: when opening properties for the second time, the tags are escaped twice
**Describe the bug**

**To Reproduce**

https://github.com/serilog-contrib/serilog-ui/assets/8641495/e54390a0-e5ba-4251-86b4-18203029248a

1. Open properties of a row
2. Close the modal
3. Open again
4. Observe that `<``>` are encoded.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 
Win11, tested with firefox and chrome

**Smartphone (please complete the following information):**

**Additional context**

Taking a quick look now.

### PR DESCRIPTION
**Pull request by followynne**
This PR fixes #99. It

- pretty-prints XML only on first modal opening
- replaces custom XML formatting with external library

### CODE REVIEW

**Review by mo-esmp — APPROVED** [review]

**Comment by mo-esmp** [comment]
@followynne After reviewing and merging PRs [95](https://github.com/serilog-contrib/serilog-ui/pull/95) and [98](https://github.com/serilog-contrib/serilog-ui/pull/98), would you like to publish the nuget package yourself?

**Comment by followynne** [comment]
@mo-esmp

That's fine, as you like 😊 
If you want, I could try fixing the datetime rendering issue and publish a nuget beta with the latest changes, to let users test it and do a first nuget publish?

**Comment by mo-esmp** [comment]
It sounds good to me. Let's publish a beta version first and thanks again for your effort.

**Comment by followynne** [comment]
Awesome! Thanks a lot to you 🤗

**Pull request merged**
